name: ci-config
description: config ci config
author: Cartera Mesh

branding:
  icon: scissors
  color: black

# Define your inputs here.
inputs:
  config:
    description: file path or JSON string
    required: true
  runner:
    description: github runner name
    required: false

# Define your outputs here.
outputs:
  config:
    description: JSON string of the config

runs:
  using: node24
  main: dist/index.js
