global:
  # to match $RUNNER_OS
  packages:
    Linux: ''
    macOS: ''
    Windows: ''
  toolchains:
    - stable
    - nightly
  features:
    - default
  rustlog: info
  fireblocks:
    enabled: false
    set-env-vars: true
ai:
  enabled: true
  allowed_bots: '*'
  claude_args: |
    --allowedTools "mcp__github_inline_comment__create_inline_comment,Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*)"

  use_sticky_comment: false
  track_progress: true
  prompt: |
    REPO: ${{ github.repository }}
    PR NUMBER: ${{ github.event.pull_request.number }}

    Perform a comprehensive code review with the following focus areas:

    1. **Code Quality**
       - Clean code principles and best practices
       - Proper error handling and edge cases
       - Code readability and maintainability

    2. **Security**
       - Check for potential security vulnerabilities
       - Validate input sanitization
       - Review authentication/authorization logic
       - Check API documentation accuracy

    Provide detailed feedback using inline comments for ONLY issues, no praise inline comments.
    Use top-level comments for general observations or praise
    Do not be shy, I am a big boy and can handle criticism gracefully. I welcome feedback and suggestions.

  # https://code.claude.com/docs/en/settings
  settings: |
    {
      "env": {
        "DUMMY": "true",
      }
    }
release:
  cargo-publish: true # release to cargo, otherwise just tag
  profile: 'release'
  os:
    - target: aarch64-unknown-linux-gnu
      os: ubicloud-standard-8-arm
    - target: x86_64-unknown-linux-gnu
      os: ubicloud-standard-4
    - target: aarch64-apple-darwin
      os: macos-latest
#    - target: x86_64-pc-windows-msvc
#      os: windows-latest
jobs:
  coverage:
    if: true
    continue-on-error: false
    args: ''
    run: |
      cmd="cargo llvm-cov --locked --lcov --output-path lcov-${FEATURES}.info --no-fail-fast"
      if [ "$FEATURES" == "default" ]; then
        $cmd -- --no-capture $CARGO_ARGS
      else
        $cmd --features "$FEATURES" -- --no-capture $CARGO_ARGS
      fi
    matrix:
      os: []
      toolchains:
        - stable
      features:
        - default
  fmt:
    if: true
    continue-on-error: false
    run: cargo +nightly fmt --check --all
  clippy:
    if: true
    continue-on-error: false
    flags: ''
    matrix:
      os: []
      toolchains:
        - stable
      features:
        - default

  semver:
    if: true
    continue-on-error: false
  hack:
    if: true
    continue-on-error: false
    run: cargo hack --feature-powerset check
  doc:
    if: true
    continue-on-error: false
    run: cargo +nightly docs-rs

  cargo-sort:
    if: true
    continue-on-error: false
    run: |
      if [ -f ./scripts/cargo-sort.sh ]; then
        ./scripts/cargo-sort.sh
      else
        cargo sort -c -g
      fi
  dependencies:
    if: true
    continue-on-error: false
    run: cargo machete --with-metadata

  sanitizers:
    enabled: true
    matrix:
      os: []
      features:
        - default
    address:
      if: true
      continue-on-error: false
      run: cargo test --lib --tests --no-fail-fast --target x86_64-unknown-linux-gnu -- --no-capture
    leak:
      if: true
      continue-on-error: false
      run: cargo test --target x86_64-unknown-linux-gnu  -- --no-capture
    thread:
      if: false
      continue-on-error: false
      run: cargo test --target x86_64-unknown-linux-gnu -- --test-threads=1
